/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package supervisor;

import com.mysql.jdbc.Connection;
import com.sun.glass.events.KeyEvent;
import database.DBconnect;

import hotelreservation.admin;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Sharan
 */


public class Addreceptionist extends javax.swing.JFrame {
    Connection connect = null;
ResultSet rst=null;
PreparedStatement pst=null;
    private String gender;

    
    public Addreceptionist(){
    initComponents();
    groupButton();
    connect = DBconnect.connect();
}
    /**
     * Creates new form addcashier
     */
  
    /*radio button action*/
private void groupButton( ) {

ButtonGroup bg1 = new ButtonGroup( );

bg1.add(rd1);
bg1.add(rd2);


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt7 = new javax.swing.JPasswordField();
        txt8 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 725));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 77, 77, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 108, 110, 27));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 153, 110, 21));

        txt2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });
        jPanel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 111, 136, -1));

        txt3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt3KeyTyped(evt);
            }
        });
        jPanel2.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 156, 136, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Address");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 186, 110, 24));

        txt4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 188, 136, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Contact Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 221, 110, 26));

        txt5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt5KeyTyped(evt);
            }
        });
        jPanel2.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 224, 136, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("NIC");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 85, 23));

        txt6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 136, 23));

        txt1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });
        jPanel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 77, 136, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 326, 56, -1));

        buttonGroup1.add(rd1);
        rd1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rd1.setText("Male");
        rd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd1ActionPerformed(evt);
            }
        });
        jPanel2.add(rd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 326, -1, -1));

        buttonGroup1.add(rd2);
        rd2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rd2.setText("Female");
        rd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd2ActionPerformed(evt);
            }
        });
        jPanel2.add(rd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 326, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("Confirm Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 153, 117, 27));

        lbl1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 117, 14));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Cashier ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("Create Password");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 114, 100, -1));

        txt7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 111, 113, -1));

        txt8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });
        txt8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt8KeyReleased(evt);
            }
        });
        jPanel2.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 156, 113, -1));

        jButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        lbl2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 163, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 600, 410));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Add a New Reseptionist");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 200, 39));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           admin ad = new admin();
             ad.setVisible(true); 
              this.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

       Addreceptionistclass adc = new Addreceptionistclass();
        
adc.setId(txt1.getText());
adc.setFname(txt2.getText());
adc.setLname(txt3.getText());
adc.setAdd(txt4.getText());
adc.setCno(txt5.getText());
adc.setNic(txt6.getText());
adc.setSex(gender);
adc.setCreatepw(txt7.getText());
adc.setConfrimpw(txt8.getText());
adc.addReceptionist();

           
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyReleased

        String idd="";
  String res="";
  
       lbl1.setText(null);
            try {
            String sql="select * from login";
            pst=connect.prepareStatement(sql);
            rst = pst.executeQuery(sql);
        
   while(rst.next()) {
            lbl1.setText(null);
             res=txt1.getText();
           idd=rst.getString("userId");
           
            if(idd.equals(res))
            {
                lbl1.setText("Not Available");
            }
            else
            {
                lbl1.setText("Available");
            }
            
        }
   
        } catch (SQLException ex) {
            Logger.getLogger(Addreceptionist.class.getName()).log(Level.SEVERE, null, ex);
        }                 
            
          
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_txt1KeyReleased

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_txt1KeyTyped

    private void txt8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt8KeyReleased
lbl2.setText(null);
        String g1=txt7.getText();
             String g2=txt8.getText();
             if( g1.equals(g2))
             {
                 lbl2.setText("matched");
                
             }
                else
             {
                 
                 lbl2.setText("password not match");
             }        // TODO add your handling code here:
    }//GEN-LAST:event_txt8KeyReleased

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8ActionPerformed

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
char c=evt.getKeyChar();
if((Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
        
else {
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txt2KeyTyped

    private void txt3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyTyped
char c=evt.getKeyChar();
if((Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
        
else {
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txt3KeyTyped

    private void txt5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyTyped
char c=evt.getKeyChar();
if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
        
else {
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txt5KeyTyped

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void rd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd1ActionPerformed
gender="Male";        // TODO add your handling code here:
    }//GEN-LAST:event_rd1ActionPerformed

    private void rd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd2ActionPerformed
gender="Female";        // TODO add your handling code here:
    }//GEN-LAST:event_rd2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addreceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addreceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addreceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addreceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addreceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JPasswordField txt7;
    private javax.swing.JPasswordField txt8;
    // End of variables declaration//GEN-END:variables
}
