/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelreservation;

import database.DBconnect;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Sharan
 */
public class Checkout extends javax.swing.JFrame {
Connection connect = null;
ResultSet rst=null;
PreparedStatement pst=null;
Statement st = null;
    /**
     * Creates new form Checkout
     */
    public Checkout() {
        initComponents();
        connect = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txt26 = new javax.swing.JTextField();
        txt27 = new javax.swing.JTextField();
        txt28 = new javax.swing.JTextField();
        txt29 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt30 = new javax.swing.JTextField();
        txt31 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt25 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl5 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        txt10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt22 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Checkout");
        setPreferredSize(new java.awt.Dimension(1280, 725));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Checkout Guest");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setText("Search");

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        jButton4.setText("Go");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tbl4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Guesr ID", "Guest Last Name", "NIC number", "Room no", "Room charge", "Date in", "Date out"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl4);

        jButton1.setText("Checkout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setText("PRINT BILL");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("REFRESH BILL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txt26.setEditable(false);

        txt27.setEditable(false);

        txt28.setEditable(false);

        txt29.setEditable(false);

        jLabel10.setText("Pay for Days");

        jLabel11.setText("More days to pay");

        jLabel12.setText("Charge for Extended days");

        jLabel13.setText("Total");

        txt30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt30KeyReleased(evt);
            }
        });

        txt31.setEditable(false);

        jLabel3.setText("Paid Amount");

        jLabel5.setText("Balance");

        txt25.setEditable(false);

        jLabel7.setText("room no");

        txta.setEditable(false);
        txta.setColumns(20);
        txta.setRows(5);
        jScrollPane2.setViewportView(txta);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt26)
                            .addComponent(txt27)
                            .addComponent(txt28)
                            .addComponent(txt29, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(txt30)
                            .addComponent(txt31)
                            .addComponent(txt25))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addGap(111, 111, 111)
                                .addComponent(jButton8))
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8)
                                .addComponent(jButton1))
                            .addComponent(jButton9))))
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("NIC No", jPanel4);

        jLabel6.setText("Search");

        jButton5.setText("Go");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tbl5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Guesr ID", "Guest Last Name", "NIC number", "Room no", "Room charge", "Date in", "Date out"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl5MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbl5);

        jButton7.setText("Checkout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txt10.setEditable(false);

        jLabel14.setText("Pay for Days");

        jLabel15.setText("More days to pay");

        jLabel16.setText("Charge for Extended days");

        jLabel17.setText("Total");

        txt7.setEditable(false);

        txt8.setEditable(false);

        txt9.setEditable(false);
        txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt9ActionPerformed(evt);
            }
        });

        jButton10.setText("PRINT BILL");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("REFRESH BILL");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        txt11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt11KeyReleased(evt);
            }
        });

        txt12.setEditable(false);

        jLabel8.setText("Paid Amount");

        jLabel9.setText("Balance");

        txt22.setEditable(false);

        jLabel18.setText("room no");

        txta1.setEditable(false);
        txta1.setColumns(20);
        txta1.setRows(5);
        jScrollPane1.setViewportView(txta1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton5)
                                        .addGap(95, 95, 95))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel18))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt7)
                                            .addComponent(txt8)
                                            .addComponent(txt9)
                                            .addComponent(txt10)
                                            .addComponent(txt11)
                                            .addComponent(txt12)
                                            .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(54, 54, 54)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addGap(111, 111, 111)
                                        .addComponent(jButton10))
                                    .addComponent(jScrollPane1))
                                .addGap(119, 119, 119))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(34, 34, 34))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton11)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Room No", jPanel5);

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(522, 522, 522)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 String sid =txt2.getText();
         String idd;
         String idd1;
         String idd2;
         String idd3;
         String idd4;
         String idd5;
         String idd6;
         
         
     try {
        String sql1 = "SELECT * FROM room_info where nic = '"+sid+"'";
        pst=connect.prepareStatement(sql1);
        rst = pst.executeQuery(sql1);
        
        int i=0;
          
        while(rst.next()) {
           idd=rst.getString("guestID");
           idd1=rst.getString("fName");
           idd2=rst.getString("nic");
           idd3=rst.getString("room_no");
           idd4=rst.getString("room_charge");
           idd5=rst.getString("date_in");
           idd6=rst.getString("date_out");
           
           
           
           tbl4.setValueAt(idd, i, 0);
           tbl4.setValueAt(idd1, i, 1);
           tbl4.setValueAt(idd2, i, 2);
           tbl4.setValueAt(idd3, i, 3);
           tbl4.setValueAt(idd4, i, 4);
           tbl4.setValueAt(idd5, i, 5);
           tbl4.setValueAt(idd6, i, 6);
          i++;
            
        
        
        }
       
        
        
        
      }
     catch (SQLException e ) {
    JOptionPane.showMessageDialog(null, e);
     }
        
         
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if((!"0".equals(txt27.getText()))&&!"".equals(txt27.getText())){
    JOptionPane.showMessageDialog(null, "All Field Requred!");
}
else if("".equals(txt27.getText())){ 
    JOptionPane.showMessageDialog(null, "Please select room info!");
}
else{int dbb =   JOptionPane.showConfirmDialog (null, "Have you print the bill Already!","Warning",JOptionPane.YES_NO_OPTION);
     if(dbb == JOptionPane.YES_OPTION){
     
        try{
            
        String sid =txt25.getText();
      st= connect.createStatement();
      String sql ="DELETE  FROM room_info where room_no ="+sid+""; 
      String sql2 ="DELETE  FROM search where room_no ="+sid+""; 
      st.executeUpdate(sql);
       st.executeUpdate(sql2);
     
       
     int rs = Integer.parseInt(txt25.getText());
    
    
 
     


if(rs<=199){
    
String sql6="UPDATE single_rooms SET status='Available' WHERE room_no="+sid+"";
pst = connect.prepareStatement(sql6);
pst.execute();
}

else if((rs<=299)&&(rs>199)){
    
String sql6="UPDATE double_rooms SET status='Available' WHERE room_no="+sid+"";
pst = connect.prepareStatement(sql6);
pst.execute();
}
else if((rs<=399)&&(rs>299)){
    
String sql6="UPDATE thrible_rooms SET status='Available' WHERE room_no="+sid+"";
pst = connect.prepareStatement(sql6);
pst.execute();
}
       
        
         JOptionPane.showMessageDialog(null, "Checkout completed !");
        for(int i=0; i<3; i++){
            tbl4.setValueAt("", i, 0);
           tbl4.setValueAt("", i, 1);
           tbl4.setValueAt("", i, 2);
           tbl4.setValueAt("", i, 3);
           tbl4.setValueAt("", i, 4);
           tbl4.setValueAt("", i, 5);
           tbl4.setValueAt("", i, 6);
            
        }
        txt2.setText(null);
        txt22.setText(null);
        }
        catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }

}
           

    
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    receptionist rsp = new receptionist();
     rsp.setVisible(true);
     this.setVisible(false);
        



// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl4MouseClicked
     
    
            //table click
txt25.setText("");
            txt26.setText("");
            txt27.setText("");
        txt28.setText("");
        txt29.setText("");
        txt30.setText("");
        txt31.setText("");
            int row=tbl4.getSelectedRow();
        
        String Table_click=(tbl4.getModel().getValueAt(row,3).toString());
               

        //get room no from table click and check database
        txt25.setText(Table_click);
        try {
        String sql1 = "SELECT * FROM room_info where room_no = '"+Table_click+"'";
        pst=connect.prepareStatement(sql1);
        rst = pst.executeQuery(sql1);
        
       
          
        while(rst.next()) {
        String   idd=rst.getString("no_of_days");
        String s2=rst.getString("date_out"); 
        String idd1=rst.getString("room_charge");
           
        txt26.setText(idd);
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
LocalDateTime now = LocalDateTime.now();
String s1=(dtf.format(now));
            
       SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");

        Date date1;
         Date date2;
        
            date1 = f.parse(s1);
            date2 = f.parse(s2);
            System.out.println(f.format(date1));
            Calendar day1 = Calendar.getInstance();
    Calendar day2 = Calendar.getInstance(); 
    day1.setTime(date1);
    day2.setTime(date2);
String v3="";
    int daysBetween = day1.get(Calendar.DAY_OF_YEAR) - day2.get(Calendar.DAY_OF_YEAR);
     v3=Integer.toString(daysBetween);
    if(0>=daysBetween){
        txt27.setText("0");
        txt28.setText("0");
        txt29.setText("0");
        txt30.setText("0");
        txt31.setText("0");
    }
    else{
    txt27.setText(v3);  
    int result2 = Integer.parseInt(idd1);
     int result = Integer.parseInt(v3);
    
    
    int tot=result*result2;
    String v4=Integer.toString(tot);
    txt28.setText(v4);
    txt29.setText(v4);
    
    }
        
        }
       
        
        
        
      }
      catch (ParseException ex) {
        Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
    }
    
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_tbl4MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
if((!"0".equals(txt8.getText()))&&!"".equals(txt8.getText())){
    JOptionPane.showMessageDialog(null, "All Field Requred!");
}
else if("".equals(txt8.getText())){ 
    JOptionPane.showMessageDialog(null, "Please select room info!");
}
else{  
        try{
            
        String sid =txt22.getText();
      st= connect.createStatement();
      String sql ="DELETE  FROM room_info where room_no ="+sid+""; 
      String sql2 ="DELETE  FROM search where room_no ="+sid+""; 
      st.executeUpdate(sql);
       st.executeUpdate(sql2);
     
       
     int rs = Integer.parseInt(txt22.getText());
    
    
 
     //String v3=Integer.toString(tot);


if(rs<=199){
    
String sql6="UPDATE single_rooms SET status='Available' WHERE room_no="+sid+"";
pst = connect.prepareStatement(sql6);
pst.execute();
}

else if((rs<=299)&&(rs>199)){
    
String sql6="UPDATE double_rooms SET status='Available' WHERE room_no="+sid+"";
pst = connect.prepareStatement(sql6);
pst.execute();
}
else if((rs<=399)&&(rs>299)){
    
String sql6="UPDATE thrible_rooms SET status='Available' WHERE room_no="+sid+"";
pst = connect.prepareStatement(sql6);
pst.execute();
}
       
        
         JOptionPane.showMessageDialog(null, "Checkout completed!");
        for(int i=0; i<3; i++){
            tbl5.setValueAt("", i, 0);
           tbl5.setValueAt("", i, 1);
           tbl5.setValueAt("", i, 2);
           tbl5.setValueAt("", i, 3);
           tbl5.setValueAt("", i, 4);
           tbl5.setValueAt("", i, 5);
           tbl5.setValueAt("", i, 6);
            
        }
        txt3.setText(null);
        
        txt25.setText(null);
        }
        catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

         String sid =txt25.getText();
        String idd="";
        String idd1="";
        String idd2="";
        String idd3="";
        String idd4="";
        String idd5="";
        String idd6="";
        String idd7="";

        try {
            String sql1 = "SELECT * FROM room_info where room_no = '"+sid+"'";
            pst=connect.prepareStatement(sql1);
            rst = pst.executeQuery(sql1);

           

            while(rst.next()) {
                idd=rst.getString("guestID");
                idd1=rst.getString("fName");
                idd2=rst.getString("nic");
                idd3=rst.getString("room_no");
                idd4=rst.getString("room_charge");
                idd5=rst.getString("date_in");
                idd6=rst.getString("date_out");
                idd7=rst.getString("no_of_days");

            }
        String exprc=txt28.getText();
        
        int result2 = Integer.parseInt(idd4);
     int result = Integer.parseInt(idd7);
     int result1 = Integer.parseInt(exprc);
    
    
    int tot=result*result2;
    String v4=Integer.toString(tot);
    String v5=Integer.toString(tot+result1);
        
        
        
        
        String mText= "                                 ZARAH HOTEL                               \n"
        + "--------------------------------------------------------------------------\n"
        + "Guest Name : " +idd1+ "\n\n"
        + "Room no    : "+sid+"\n\n"
        + "Room Price : "+idd4+"\n\n"
        + "Charge For Days : "+idd7+" / Rs "+v4+".00\n\n"
        + "Extended Days   : "+txt27.getText()+" / Rs "+txt28.getText()+".00\n\n"
        +"Total Price      : Rs "+v5+".00\n\n"
        + "--------------------------------------------------------------------------\n\n"
        +"                                 THANK YOU                                \n"
        +"ZARAH Hotel\n"
        +"Airport road\n"
        +"Katunayake.\n"
        +"Fax : 032222213"
        +"Tel : 032222214";
         
        txta.setText(mText);       
    }                                         

    catch (SQLException ex) {
        Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
    }
        
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
if(!"".equals(txta.getText())){
    try {
        boolean complete=txta.print();
        if(complete){
            JOptionPane.showMessageDialog(null, "done printing","information",JOptionPane.INFORMATION_MESSAGE);
            
        }
        else{
            JOptionPane.showMessageDialog(null,"printing","printer",JOptionPane.ERROR_MESSAGE);
        }
    } catch (PrinterException ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
    }
else{
    JOptionPane.showMessageDialog(null, "Please press refresh bill button!");
}                // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String sid =txt3.getText();
        String idd;
        String idd1;
        String idd2;
        String idd3;
        String idd4;
        String idd5;
        String idd6;

        try {
            String sql1 = "SELECT * FROM room_info where room_no = '"+sid+"'";
            pst=connect.prepareStatement(sql1);
            rst = pst.executeQuery(sql1);

            int i=0;

            while(rst.next()) {
                idd=rst.getString("guestID");
                idd1=rst.getString("fName");
                idd2=rst.getString("nic");
                idd3=rst.getString("room_no");
                idd4=rst.getString("room_charge");
                idd5=rst.getString("date_in");
                idd6=rst.getString("date_out");

                tbl5.setValueAt(idd, i, 0);
                tbl5.setValueAt(idd1, i, 1);
                tbl5.setValueAt(idd2, i, 2);
                tbl5.setValueAt(idd3, i, 3);
                tbl5.setValueAt(idd4, i, 4);
                tbl5.setValueAt(idd5, i, 5);
                tbl5.setValueAt(idd6, i, 6);
                i++;

            }

        }
        catch (SQLException e ) {
            JOptionPane.showMessageDialog(null, e);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       String sid =txt22.getText();
        String idd="";
        String idd1="";
        String idd2="";
        String idd3="";
        String idd4="";
        String idd5="";
        String idd6="";
        String idd7="";

        try {
            String sql1 = "SELECT * FROM room_info where room_no = '"+sid+"'";
            pst=connect.prepareStatement(sql1);
            rst = pst.executeQuery(sql1);

            int i=0;

            while(rst.next()) {
                idd=rst.getString("guestID");
                idd1=rst.getString("fName");
                idd2=rst.getString("nic");
                idd3=rst.getString("room_no");
                idd4=rst.getString("room_charge");
                idd5=rst.getString("date_in");
                idd6=rst.getString("date_out");
                idd7=rst.getString("no_of_days");

            }
        String exprc=txt9.getText();
        
        int result2 = Integer.parseInt(idd4);
     int result = Integer.parseInt(idd7);
     int result1 = Integer.parseInt(exprc);
    
    
    int tot=result*result2;
    String v4=Integer.toString(tot);
    String v5=Integer.toString(tot+result1);
        
        
        
        
        String mText= "                                 SARA HOTEL                               \n"
        + "--------------------------------------------------------------------------\n"
        + "Guest Name : " +idd1+ "\n\n"
        + "Room no    : "+sid+"\n\n"
        + "Room Price : "+idd4+"\n\n"
        + "Charge For Days : "+idd7+" / Rs "+v4+".00\n\n"
        + "Extended Days   : "+txt8.getText()+" / Rs "+txt9.getText()+".00\n\n"
        +"Total Price      : Rs "+v5+".00\n\n"
        + "--------------------------------------------------------------------------\n\n"
        +"                                 THANK YOU                                \n"
        +"Sarah Hotel\n"
        +"Airport road\n"
        +"Katunayake.\n"
        +"Fax : 032222213"
        +"Tel : 032222214";
         
        txta1.setText(mText);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    catch (SQLException ex) {
        Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        if(!"".equals(txta1.getText())){
            try {
                boolean complete=txta1.print();
                if(complete){
                    JOptionPane.showMessageDialog(null, "done printing","information",JOptionPane.INFORMATION_MESSAGE);

                }
                else{
                    JOptionPane.showMessageDialog(null,"printing","printer",JOptionPane.ERROR_MESSAGE);
                }
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please press refresh bill button!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl5MouseClicked

        txt22.setText("");
        txt7.setText("");
        txt8.setText("");
        txt9.setText("");
        txt10.setText("");
        txt11.setText("");
        txt12.setText("");
        //get room number from table click
        int row=tbl5.getSelectedRow();

        String Table_click=(tbl5.getModel().getValueAt(row,3).toString());

        txt22.setText(Table_click);
         try {
        String sql1 = "SELECT * FROM room_info where room_no = '"+Table_click+"'";
        pst=connect.prepareStatement(sql1);
        rst = pst.executeQuery(sql1);
        
       
          
        while(rst.next()) {
        String   idd=rst.getString("no_of_days");
        String s2=rst.getString("date_out"); 
        String idd1=rst.getString("room_charge");
           
        txt7.setText(idd);
        //get today date
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
LocalDateTime now = LocalDateTime.now();
String s1=(dtf.format(now));
            //days calculate between today and chekout date
       SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");

        Date date1;
         Date date2;
        //parse string date to date typeformate
            date1 = f.parse(s1);
            date2 = f.parse(s2);
            System.out.println(f.format(date1));
            Calendar day1 = Calendar.getInstance();
    Calendar day2 = Calendar.getInstance(); 
    day1.setTime(date1);
    day2.setTime(date2);
String v3="";
    int daysBetween = day1.get(Calendar.DAY_OF_YEAR) - day2.get(Calendar.DAY_OF_YEAR);
     v3=Integer.toString(daysBetween);
    if(0>=daysBetween){
        txt8.setText("0");//if checkout date equal to roday date set all fields0
        txt9.setText("0");
        txt10.setText("0");
        txt11.setText("0");
        txt12.setText("0");
    }
    else{
    txt8.setText(v3);  //if cusomer have to pay more days
    int result2 = Integer.parseInt(idd1);
     int result = Integer.parseInt(v3);
    
    
    int tot=result*result2;
    String v4=Integer.toString(tot);
    txt9.setText(v4);
    txt10.setText(v4);
    
    }
        //two catch clause one for sql other for date parsing 
        }} catch (SQLException ex) {
        Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(Checkout.class.getName()).log(Level.SEVERE, null, ex);
    }
          
    }//GEN-LAST:event_tbl5MouseClicked

    private void txt30KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt30KeyReleased
txt31.setText("");
        String t=txt30.getText();

int result3=Integer.parseInt(txt30.getText());
        int result2 = Integer.parseInt(txt29.getText());
        int tot=result3-result2;
                 String v3=Integer.toString(tot);
                 txt31.setText(v3);        // TODO add your handling code here:
    }//GEN-LAST:event_txt30KeyReleased

    private void txt11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt11KeyReleased
      txt12.setText("");
        String t=txt11.getText();

int result3=Integer.parseInt(txt11.getText());
        int result2 = Integer.parseInt(txt10.getText());
        int tot=result3-result2;
                 String v3=Integer.toString(tot);
                 txt12.setText(v3);    // TODO add your handling code here:
    }//GEN-LAST:event_txt11KeyReleased

    private void txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt9ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable tbl4;
    private javax.swing.JTable tbl5;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt27;
    private javax.swing.JTextField txt28;
    private javax.swing.JTextField txt29;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt30;
    private javax.swing.JTextField txt31;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    private javax.swing.JTextArea txta;
    private javax.swing.JTextArea txta1;
    // End of variables declaration//GEN-END:variables
}
